### PR TITLE
Change addon startup to services

### PR DESCRIPTION
**Pull request by bdraco**
fixes https://github.com/home-assistant/core/issues/103967
fixes https://github.com/home-assistant/core/issues/97826

### CODE REVIEW

**Comment by bdraco** [comment]
I don't have a good way to test this though.

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Might as well generate for stable and beta too I guess?

**Comment by bdraco** [comment]
It looks like they will get generated from the template upon release so probably don't have to update anything but dev AFAICT from https://github.com/esphome/home-assistant-addon/commit/23eca65264503d0ad15d9d3e771e0d18e8ac3285 and https://github.com/esphome/home-assistant-addon/blob/57295409599e88b6873ee098b19c99e8467a8933/template/addon_config.yaml#L4?

**Comment by codyc1515** [comment]
Could you please post a beta release? I can then confirm if fixed.

**Pull request merged**
